
[functions.transactions]
enabled = true
verify_jwt = true
import_map = "./functions/transactions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transactions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transactions/*.html" ]

[functions.get-pending-orders]
verify_jwt = true

[functions.get-positions]
verify_jwt = true

[functions.get-watchlist]
verify_jwt = true

[db.seed]
enabled = true
sql_paths = ["db/seed_transactions.sql", "db/indexes.sql"]
