
[functions.transactions]
verify_jwt = true

[functions.get-pending-orders]
verify_jwt = true

[functions.get-positions]
verify_jwt = true

[functions.get-watchlist]
verify_jwt = true

[db.seed]
enabled = true
sql_paths = ["db/seed_transactions.sql", "db/indexes.sql"]
